/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appchat;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dung
 */
public class ClientGui extends javax.swing.JFrame {
    private String userName, privateUserName = "";
    private DataInputStream din;
    private DataOutputStream dout;
    private DefaultListModel dlm;
    private int port;
    
    private String USER_LIST_CODE = ":;,./=";
    private String PRIVATE_MESSAGE_CODE = "#4344554@@@@@67667@@";
    private String TERMINATE_CODE = "mkoihgteazdcvgyhujb096785542AXTY";
    /**
     * Creates new form ClientGui
     */
    public ClientGui() {
        initComponents();
    }

    public ClientGui(String userName, String roomName, Socket s) {
        this.userName = userName;
        try{
            initComponents();
            dlm = new DefaultListModel();
            jListUsers.setModel(dlm);
            jLabelRoomName.setText(roomName);
            jLabelUserName.setText(userName + ":");
            jTextAreaHistory.append(String.format("--- [%s] is online.\n", userName));
            din = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());
            new Read().start();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    class Read extends Thread {
        public void run(){
            while(true){
                try {
                    String msg = din.readUTF();
                    if(msg.contains(USER_LIST_CODE)){
                        msg = msg.substring(6);
                        dlm.clear();
                        StringTokenizer str = new StringTokenizer(msg, ",");
                        while(str.hasMoreTokens()){
                            String u = str.nextToken();
                            if(!userName.equals(u)){
                                dlm.addElement(u);
                            }
                        }
                    }
                    else {
                        jTextAreaHistory.append(msg + "\n");
                    }
                }
                catch (Exception e){
                    break;
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonLogout = new javax.swing.JButton();
        jLabelRoomName = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jTextFieldInput = new javax.swing.JTextField();
        jButtonSend = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaHistory = new javax.swing.JTextArea();
        jLabelUserOnline = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListUsers = new javax.swing.JList<>();
        jButtonUnselect = new javax.swing.JButton();

        jTextArea1.setColumns(10);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Group Chat Chill Chill - Client");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabelRoomName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRoomName.setText("Room Name");

        jLabelUserName.setText("userName");

        jTextFieldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessage(evt);
            }
        });

        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessage(evt);
            }
        });

        jTextAreaHistory.setEditable(false);
        jTextAreaHistory.setColumns(20);
        jTextAreaHistory.setLineWrap(true);
        jTextAreaHistory.setRows(5);
        jTextAreaHistory.setMaximumSize(new java.awt.Dimension(113, 21));
        jScrollPane3.setViewportView(jTextAreaHistory);

        jLabelUserOnline.setText("Online users:");

        jListUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListUsersValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListUsers);

        jButtonUnselect.setText("Unselect");
        jButtonUnselect.setEnabled(false);
        jButtonUnselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnselectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRoomName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUnselect)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonLogout)
                        .addComponent(jLabelRoomName))
                    .addComponent(jLabelUserOnline, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSend)
                    .addComponent(jTextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserName)
                    .addComponent(jButtonUnselect))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        try {
            dout.writeUTF(TERMINATE_CODE);
            this.dispose();
            new Login().setVisible(true);
        }
        catch (Exception e){
            Logger.getLogger(ClientGui.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void sendMessage(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessage
        // TODO add your handling code here:
        try {
            String msg = jTextFieldInput.getText();
            if(!privateUserName.isEmpty()){
                String serverMsg = PRIVATE_MESSAGE_CODE + privateUserName + ":" + msg;
                dout.writeUTF(serverMsg);
                jTextFieldInput.setText("");
                jTextAreaHistory.append("You to [" + privateUserName + "]: " + msg + "\n");
            }
            else {
                dout.writeUTF(msg);
                jTextFieldInput.setText("");
                jTextAreaHistory.append("You: " + msg + "\n");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "User does not exist anymore.");
        }
    }//GEN-LAST:event_sendMessage

    private void jListUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListUsersValueChanged
        // TODO add your handling code here:
        String selectedUser = jListUsers.getSelectedValue();
        if(selectedUser != null){
            privateUserName = selectedUser;
            jButtonUnselect.setEnabled(true);
        }
        else {
            privateUserName = "";
            jButtonUnselect.setEnabled(false);
        }
    }//GEN-LAST:event_jListUsersValueChanged

    private void jButtonUnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnselectActionPerformed
        // TODO add your handling code here:
        jListUsers.clearSelection();
    }//GEN-LAST:event_jButtonUnselectActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            dout.writeUTF(TERMINATE_CODE);
            this.dispose();
        }
        catch (Exception e){
            Logger.getLogger(ClientGui.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_formWindowClosing
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JButton jButtonUnselect;
    private javax.swing.JLabel jLabelRoomName;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelUserOnline;
    private javax.swing.JList<String> jListUsers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaHistory;
    private javax.swing.JTextField jTextFieldInput;
    // End of variables declaration//GEN-END:variables
}